// Generates a self-contained SVG map of Western Europe from Natural Earth data
// (world-atlas TopoJSON, public domain). Projects both the country outlines and
// the journey's city GPS coordinates with the SAME projection so the markers
// land exactly on the map. Output: src/data/mapData.ts
//
// Prerequisite — fetch the public-domain source once (git-ignored):
//   curl -sSL https://cdn.jsdelivr.net/npm/world-atlas@2/countries-50m.json -o scripts/countries-50m.json
// Run: node scripts/generate-map.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { geoMercator, geoPath } from "d3-geo";
import { feature, mesh } from "topojson-client";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

// Cities of the journey (must stay in sync with src/data/journey.ts).
const cities = {
  dijon: [5.041, 47.322],
  liverpool: [-2.992, 53.408],
  barcelona: [2.17, 41.39],
  strasbourg: [7.752, 48.573],
  paris: [2.352, 48.857],
  berlin: [13.405, 52.52],
  nantes: [-1.554, 47.218],
};

// Geographic frame (with margin around the extreme cities) to crop the map on.
// MultiPoint of the corners → winding-independent bbox (a spherical Polygon with
// reversed winding would be read by d3-geo as "the whole globe minus the box").
const bounds = {
  type: "MultiPoint",
  coordinates: [[-11, 36], [20, 36], [20, 58], [-11, 58]],
};

const W = 1000;

const topo = JSON.parse(readFileSync(join(__dirname, "countries-50m.json"), "utf8"));

// Fit the projection to the frame width, then read the resulting pixel bounds.
const projection = geoMercator().fitWidth(W, bounds);
const path = geoPath(projection);
const [[x0, y0], [x1, y1]] = path.bounds(bounds);

const width = Math.ceil(x1 - x0);
const height = Math.ceil(y1 - y0);

// Clip the streamed geometry to the visible rectangle so we only emit Western
// Europe instead of the whole world's landmass (drops the path size ~10x).
projection.clipExtent([[x0, y0], [x1, y1]]);

const round = (s) => s.replace(/-?\d+\.\d+/g, (m) => Number(m).toFixed(1));

const land = round(path(feature(topo, topo.objects.land)));
const borders = round(path(mesh(topo, topo.objects.countries, (a, b) => a !== b)));

const projectedCities = Object.fromEntries(
  Object.entries(cities).map(([id, lnglat]) => {
    const [x, y] = projection(lnglat);
    return [id, { x: Number(x.toFixed(1)), y: Number(y.toFixed(1)) }];
  })
);

const out = `// AUTO-GENERATED by scripts/generate-map.mjs — do not edit by hand.
// Self-contained SVG geometry for the journey map (Natural Earth, public domain).

export type CityPoint = { x: number; y: number };

export const mapData = {
  viewBox: "${x0.toFixed(1)} ${y0.toFixed(1)} ${width} ${height}",
  width: ${width},
  height: ${height},
  land: ${JSON.stringify(land)},
  borders: ${JSON.stringify(borders)},
  cities: ${JSON.stringify(projectedCities)} as Record<string, CityPoint>,
};
`;

writeFileSync(join(root, "src/data/mapData.ts"), out);

console.log("mapData.ts written");
console.log("  viewBox:", `${x0.toFixed(1)} ${y0.toFixed(1)} ${width} ${height}`);
console.log("  land path:", land.length, "chars | borders:", borders.length, "chars");
console.log("  cities:", projectedCities);
